---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    prefix: "build(deps)"
    schedule:
      interval: "weekly"
    groups:
      docker-all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    prefix: "build(deps)"
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    prefix: "build(deps)"
    schedule:
      interval: "weekly"
    groups:
      gomod-all:
        patterns:
          - "*"
