language: go
go:
  - 1.13.7
env:
  global:
    - SHA512_CMD=sha512sum
    - GO111MODULE=on
matrix:
  include:
  - os: linux
    dist: bionic
  - os: osx
    env:
      - SHA512_CMD="shasum -a 512"
  - os: windows
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run -v; fi
  - export DELIVERABLE="dip-${TRAVIS_OS_NAME}"
  - go build -ldflags "-X dip/cmd.Version=${TRAVIS_TAG}" -o $DELIVERABLE
  - $SHA512_CMD $DELIVERABLE > ${DELIVERABLE}.sha512.txt
  - chmod +x $DELIVERABLE
  - if [ $TRAVIS_OS_NAME == linux ]; then cp $DELIVERABLE dip && ./testing/integration.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then bash <(curl -s https://codecov.io/bash); fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $DELIVERABLE
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true
