language: go
go:
  - 1.15.6
env:
  global:
    - SHA512_CMD=sha512sum
    - GO111MODULE=on
matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      env:
        - SHA512_CMD="shasum -a 512"
    - os: windows
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -L https://github.com/030/a2deb/releases/download/1.0.0/a2deb_1.0.0-0.deb -o a2deb.deb && sudo apt update -y && sudo apt-get -y install ./a2deb.deb bats; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21.0 golangci-lint run -v; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then go test -short -cover -v -coverprofile=coverage.txt -covermode=atomic ./...; fi
  - export DELIVERABLE="dip-${TRAVIS_OS_NAME}"
  - go build -ldflags "-X main.ver=${TRAVIS_TAG}" -o $DELIVERABLE
  - $SHA512_CMD $DELIVERABLE > ${DELIVERABLE}.sha512.txt
  - chmod +x $DELIVERABLE
  - if [ $TRAVIS_OS_NAME == linux ]; then cp $DELIVERABLE dip && ./testing/integration.sh; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -n "${TRAVIS_TAG}" ]; then cp $DELIVERABLE dip && a2deb -app dip -version ${TRAVIS_TAG} -maintainer "030 <chocolatey030@gmail.com>" -description "Docker Image Patrol"; fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - dip_${TRAVIS_TAG}-0.deb
    - $DELIVERABLE
    - ${DELIVERABLE}.sha512.txt
  skip_cleanup: true
  on:
    tags: true
