---
apiVersion: v1
kind: Namespace
metadata:
  name: dip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dip
  namespace: dip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dip
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dip
  namespace: dip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dip
subjects:
  - kind: ServiceAccount
    name: dip
    namespace: dip
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dip
  namespace: dip
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dip
          containers:
            - name: dip
              image: utrecht/dip:2.2.0
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "25m"
                requests:
                  memory: "4Mi"
                  cpu: "5m"
              imagePullPolicy: IfNotPresent
              command:
                - dip
              args:
                - k8s
                - -config
                - /home/dip/.dip/config.yml
              volumeMounts:
                - name: dip-config
                  mountPath: /home/dip/.dip
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: dip-config
              secret:
                secretName: dip-config
