---
name: CodeCov
'on':
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
      - name: Unit test
        run: |
          go test -short -cover -v -coverprofile=coverage.txt \
          -covermode=atomic ./...
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          flags: unittests
          verbose: true
